wallpaper {
    monitor = eDP-1
    path = /home/ehwazm/Documents/Wallpapers/wallpaperflare.com_wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/ehwazm/Documents/Wallpapers/1369551.jpeg
    fit_mode = cover
}

splash = false
# ...
