wallpaper {
    monitor = eDP-1
    path = ~/Documents/Wallpapers/1341796.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Documents/Wallpapers/1177159.jpg
    fit_mode = cover
}

splash = false
# ...
