import = [
    "/home/kai/.alacritty-colorscheme/themes/tokyonight_night.toml",
]

[colors]
indexed_colors = [
    { color = "#FAB387", index = 16 },
    { color = "#F5E0DC", index = 17 },
]

[colors.bright]
black = "#5D5D5D"
blue = "#0071FF"
cyan = "#4BB8FD"
green = "#7BC91F"
magenta = "#FF1D62"
red = "#FF361E"
white = "#A020F0"
yellow = "#FFD00A"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.normal]
black = "#303030"
blue = "#004F9E"
cyan = "#2AA7E7"
green = "#6AB017"
magenta = "#EC0048"
red = "#E1321A"
white = "#F2F2F2"
yellow = "#FFC005"

[colors.primary]
background = "#101010"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#F2F2F2"

[font]
size = 9

[cursor]

style = {shape = "Beam", blinking = "Never"}

vi_mode_style = {shape = "Beam", blinking = "Never"}

[window]
opacity = 0.85
decorations = "None"
dynamic_title =  true
