# autogenerated by txs
#include:amstext
#include:array
#include:expl3
#include:l3keys2e
#include:textcomp
#include:translator
#include:xparse
#include:xspace
\DeclareBinaryPrefix{arg1}#S
\DeclareSIPostPower{arg1}#S
\DeclareSIPrePower{arg1}#S
\DeclareSIPrefix{arg1}#S
\DeclareSIQualifier{arg1}#S
\DeclareSIUnit#S
\DeclareSIUnitWithOptions{arg1}#S
\DeclareSIUnit[optarg1]#S
\SI#S
\SIInBookmark#S
\SIInBookmark[optarg1]#S
\SI[optarg1]#S
\SIlist#S
\SIlist[optarg1]#S
\SIrange#S
\SIrange[optarg1]#S
\ang#S
\ang[optarg1]#S
\num#S
\numInBookmark#S
\numInBookmark[optarg1]#S
\num[optarg1]#S
\numlist#S
\numlist[optarg1]#S
\numrange#S
\numrangeInBookmark#S
\numrangeInBookmark[optarg1]#S
\numrange[optarg1]#S
\si#S
\siInBookmark#S
\siInBookmark[optarg1]#S
\si[optarg1]#S
\sisetup{arg1}#S
\tablenum#S
\tablenum[optarg1]#S
\DeclareBinaryPrefix code#S
\DeclareSIPostPower code#S
\DeclareSIPrePower code#S
\DeclareSIPrefix code#S
\DeclareSIQualifier code#S
\DeclareSIUnit code#S
\DeclareSIUnitWithOptions code#S
\SI code#S
\SIInBookmark (arg 1)#S
\SIInBookmark (arg 3)#S
\SIInBookmark code#S
\SIUnitSymbolAngstrom#S
\SIUnitSymbolArcminute#S
\SIUnitSymbolArcsecond#S
\SIUnitSymbolCelsius#S
\SIUnitSymbolDegree#S
\SIUnitSymbolMicro#S
\SIUnitSymbolOhm#S
\SIlist code#S
\SIlistInBookmark (arg 1)#S
\SIlistInBookmark code#S
\SIlistInBookmark#S
\SIrange code#S
\SIrangeInBookmark (arg 1)#S
\SIrangeInBookmark code#S
\SIrangeInBookmark#S
\__file_name=amstext.sty#S
\__file_name=array.sty#S
\__file_name=expl3.sty#S
\__file_name=l3keys2e.sty#S
\__file_name=siunitx.cfg#S
\__file_name=translator.sty#S
\__file_name=xparse.sty#S
\__file_seen_amstext.sty:#S
\__file_seen_array.sty:#S
\__file_seen_expl3.sty:#S
\__file_seen_l3keys2e.sty:#S
\__file_seen_translator.sty:#S
\__file_seen_xparse.sty:#S
\__hook amstext#S
\__hook array#S
\__hook expl3#S
\__hook l3keys2e#S
\__hook package/amstext/after#S
\__hook package/amstext/before#S
\__hook package/array/after#S
\__hook package/array/before#S
\__hook package/expl3/after#S
\__hook package/expl3/before#S
\__hook package/l3keys2e/after#S
\__hook package/l3keys2e/before#S
\__hook package/translator/after#S
\__hook package/translator/before#S
\__hook package/xparse/after#S
\__hook package/xparse/before#S
\__hook siunitx#S
\__hook translator#S
\__hook xparse#S
\__hook_next package/amstext/after#S
\__hook_next package/amstext/before#S
\__hook_next package/array/after#S
\__hook_next package/array/before#S
\__hook_next package/expl3/after#S
\__hook_next package/expl3/before#S
\__hook_next package/l3keys2e/after#S
\__hook_next package/l3keys2e/before#S
\__hook_next package/translator/after#S
\__hook_next package/translator/before#S
\__hook_next package/xparse/after#S
\__hook_next package/xparse/before#S
\__siunitx_\ampere_function:w#S
\__siunitx_\ampere_literal:w#S
\__siunitx_\angstrom_function:w#S
\__siunitx_\angstrom_literal:w#S
\__siunitx_\arcmin_function:w#S
\__siunitx_\arcmin_literal:w#S
\__siunitx_\arcminute_function:w#S
\__siunitx_\arcminute_literal:w#S
\__siunitx_\arcsecond_function:w#S
\__siunitx_\arcsecond_literal:w#S
\__siunitx_\astronomicalunit_function:w#S
\__siunitx_\astronomicalunit_literal:w#S
\__siunitx_\atomicmassunit_function:w#S
\__siunitx_\atomicmassunit_literal:w#S
\__siunitx_\atto_function:w#S
\__siunitx_\atto_literal:w#S
\__siunitx_\bar_function:w#S
\__siunitx_\bar_literal:w#S
\__siunitx_\barn_function:w#S
\__siunitx_\barn_literal:w#S
\__siunitx_\becquerel_function:w#S
\__siunitx_\becquerel_literal:w#S
\__siunitx_\bel_function:w#S
\__siunitx_\bel_literal:w#S
\__siunitx_\bohr_function:w#S
\__siunitx_\bohr_literal:w#S
\__siunitx_\candela_function:w#S
\__siunitx_\candela_literal:w#S
\__siunitx_\celsius_function:w#S
\__siunitx_\celsius_literal:w#S
\__siunitx_\centi_function:w#S
\__siunitx_\centi_literal:w#S
\__siunitx_\clight_function:w#S
\__siunitx_\clight_literal:w#S
\__siunitx_\coulomb_function:w#S
\__siunitx_\coulomb_literal:w#S
\__siunitx_\cubed_function:w#S
\__siunitx_\cubed_literal:w#S
\__siunitx_\cubic_function:w#S
\__siunitx_\cubic_literal:w#S
\__siunitx_\dalton_function:w#S
\__siunitx_\dalton_literal:w#S
\__siunitx_\day_function:w#S
\__siunitx_\day_literal:w#S
\__siunitx_\deca_function:w#S
\__siunitx_\deca_literal:w#S
\__siunitx_\deci_function:w#S
\__siunitx_\deci_literal:w#S
\__siunitx_\decibel_function:w#S
\__siunitx_\decibel_literal:w#S
\__siunitx_\degreeCelsius_function:w#S
\__siunitx_\degreeCelsius_literal:w#S
\__siunitx_\degree_function:w#S
\__siunitx_\degree_literal:w#S
\__siunitx_\deka_function:w#S
\__siunitx_\deka_literal:w#S
\__siunitx_\electronmass_function:w#S
\__siunitx_\electronmass_literal:w#S
\__siunitx_\electronvolt_function:w#S
\__siunitx_\electronvolt_literal:w#S
\__siunitx_\elementarycharge_function:w#S
\__siunitx_\elementarycharge_literal:w#S
\__siunitx_\exa_function:w#S
\__siunitx_\exa_literal:w#S
\__siunitx_\farad_function:w#S
\__siunitx_\farad_literal:w#S
\__siunitx_\femto_function:w#S
\__siunitx_\femto_literal:w#S
\__siunitx_\giga_function:w#S
\__siunitx_\giga_literal:w#S
\__siunitx_\gram_function:w#S
\__siunitx_\gram_literal:w#S
\__siunitx_\gray_function:w#S
\__siunitx_\gray_literal:w#S
\__siunitx_\hartree_function:w#S
\__siunitx_\hartree_literal:w#S
\__siunitx_\hectare_function:w#S
\__siunitx_\hectare_literal:w#S
\__siunitx_\hecto_function:w#S
\__siunitx_\hecto_literal:w#S
\__siunitx_\henry_function:w#S
\__siunitx_\henry_literal:w#S
\__siunitx_\hertz_function:w#S
\__siunitx_\hertz_literal:w#S
\__siunitx_\highlight_function:w#S
\__siunitx_\highlight_literal:w#S
\__siunitx_\hour_function:w#S
\__siunitx_\hour_literal:w#S
\__siunitx_\joule_function:w#S
\__siunitx_\joule_literal:w#S
\__siunitx_\katal_function:w#S
\__siunitx_\katal_literal:w#S
\__siunitx_\kelvin_function:w#S
\__siunitx_\kelvin_literal:w#S
\__siunitx_\kilo_function:w#S
\__siunitx_\kilo_literal:w#S
\__siunitx_\kilogram_function:w#S
\__siunitx_\kilogram_literal:w#S
\__siunitx_\knot_function:w#S
\__siunitx_\knot_literal:w#S
\__siunitx_\liter_function:w#S
\__siunitx_\liter_literal:w#S
\__siunitx_\litre_function:w#S
\__siunitx_\litre_literal:w#S
\__siunitx_\lumen_function:w#S
\__siunitx_\lumen_literal:w#S
\__siunitx_\lux_function:w#S
\__siunitx_\lux_literal:w#S
\__siunitx_\mega_function:w#S
\__siunitx_\mega_literal:w#S
\__siunitx_\meter_function:w#S
\__siunitx_\meter_literal:w#S
\__siunitx_\metre_function:w#S
\__siunitx_\metre_literal:w#S
\__siunitx_\micro_function:w#S
\__siunitx_\micro_literal:w#S
\__siunitx_\milli_function:w#S
\__siunitx_\milli_literal:w#S
\__siunitx_\minute_function:w#S
\__siunitx_\minute_literal:w#S
\__siunitx_\mmHg_function:w#S
\__siunitx_\mmHg_literal:w#S
\__siunitx_\mole_function:w#S
\__siunitx_\mole_literal:w#S
\__siunitx_\nano_function:w#S
\__siunitx_\nano_literal:w#S
\__siunitx_\nauticalmile_function:w#S
\__siunitx_\nauticalmile_literal:w#S
\__siunitx_\neper_function:w#S
\__siunitx_\neper_literal:w#S
\__siunitx_\newton_function:w#S
\__siunitx_\newton_literal:w#S
\__siunitx_\of_function:w#S
\__siunitx_\of_literal:w#S
\__siunitx_\ohm_function:w#S
\__siunitx_\ohm_literal:w#S
\__siunitx_\pascal_function:w#S
\__siunitx_\pascal_literal:w#S
\__siunitx_\per_function:w#S
\__siunitx_\per_literal:w#S
\__siunitx_\percent_function:w#S
\__siunitx_\percent_literal:w#S
\__siunitx_\peta_function:w#S
\__siunitx_\peta_literal:w#S
\__siunitx_\pico_function:w#S
\__siunitx_\pico_literal:w#S
\__siunitx_\planckbar_function:w#S
\__siunitx_\planckbar_literal:w#S
\__siunitx_\radian_function:w#S
\__siunitx_\radian_literal:w#S
\__siunitx_\raiseto_function:w#S
\__siunitx_\raiseto_literal:w#S
\__siunitx_\second_function:w#S
\__siunitx_\second_literal:w#S
\__siunitx_\siemens_function:w#S
\__siunitx_\siemens_literal:w#S
\__siunitx_\sievert_function:w#S
\__siunitx_\sievert_literal:w#S
\__siunitx_\square_function:w#S
\__siunitx_\square_literal:w#S
\__siunitx_\squared_function:w#S
\__siunitx_\squared_literal:w#S
\__siunitx_\steradian_function:w#S
\__siunitx_\steradian_literal:w#S
\__siunitx_\tera_function:w#S
\__siunitx_\tera_literal:w#S
\__siunitx_\tesla_function:w#S
\__siunitx_\tesla_literal:w#S
\__siunitx_\tonne_function:w#S
\__siunitx_\tonne_literal:w#S
\__siunitx_\tothe_function:w#S
\__siunitx_\tothe_literal:w#S
\__siunitx_\volt_function:w#S
\__siunitx_\volt_literal:w#S
\__siunitx_\watt_function:w#S
\__siunitx_\watt_literal:w#S
\__siunitx_\weber_function:w#S
\__siunitx_\weber_literal:w#S
\__siunitx_\yocto_function:w#S
\__siunitx_\yocto_literal:w#S
\__siunitx_\yotta_function:w#S
\__siunitx_\yotta_literal:w#S
\__siunitx_\zepto_function:w#S
\__siunitx_\zepto_literal:w#S
\__siunitx_\zetta_function:w#S
\__siunitx_\zetta_literal:w#S
\__siunitx_cs_if_tl:NF#S
\__siunitx_cs_if_tl:NT#S
\__siunitx_cs_if_tl:NTF#S
\__siunitx_cs_if_tl_p:N#S
\__siunitx_number_format_group_integer_setup:V#S
\__siunitx_number_if_zero:nTF#S
\__siunitx_number_if_zero_p:V#S
\__siunitx_number_if_zero_p:n#S
\__siunitx_number_in_parse:V#S
\__siunitx_number_in_parse_error:nV#S
\__siunitx_number_output:V#S
\__siunitx_number_output_parse:V#S
\__siunitx_number_preprocess:V#S
\__siunitx_number_process_scientific_engineering_0:nnn#S
\__siunitx_number_process_scientific_engineering_1:nnn#S
\__siunitx_number_process_scientific_engineering_1:nw#S
\__siunitx_number_process_scientific_engineering_2:nnn#S
\__siunitx_number_process_scientific_engineering_2_i:nw#S
\__siunitx_number_process_scientific_engineering_2_ii:nw#S
\__siunitx_print:nV#S
\__siunitx_tl_put_left_math:NV#S
\__siunitx_unit_in:Vn#S
\__siunitx_unit_mathrm:n#S
\__siunitx_unit_mathsf:n#S
\__siunitx_unit_mathtt:n#S
\__siunitx_unit_output:Vn#S
\ang code#S
\clist_map_function:nc#S
\g__hook_package/amstext/after_reversed_tl#S
\g__hook_package/amstext/before_reversed_tl#S
\g__hook_package/array/after_reversed_tl#S
\g__hook_package/array/before_reversed_tl#S
\g__hook_package/expl3/after_reversed_tl#S
\g__hook_package/expl3/before_reversed_tl#S
\g__hook_package/l3keys2e/after_reversed_tl#S
\g__hook_package/l3keys2e/before_reversed_tl#S
\g__hook_package/translator/after_reversed_tl#S
\g__hook_package/translator/before_reversed_tl#S
\g__hook_package/xparse/after_reversed_tl#S
\g__hook_package/xparse/before_reversed_tl#S
\key check > siunitx/abbreviations#S
\key check > siunitx/add-arc-degree-zero#S
\key check > siunitx/add-arc-minute-zero#S
\key check > siunitx/add-arc-second-zero#S
\key check > siunitx/add-decimal-zero#S
\key check > siunitx/add-integer-zero#S
\key check > siunitx/allow-number-unit-breaks#S
\key check > siunitx/angle-symbol-over-decimal#S
\key check > siunitx/binary-units#S
\key check > siunitx/bracket-negative-numbers#S
\key check > siunitx/bracket-numbers#S
\key check > siunitx/bracket-unit-denominator#S
\key check > siunitx/copy-complex-root#S
\key check > siunitx/copy-decimal-marker#S
\key check > siunitx/detect-all#S
\key check > siunitx/detect-display-math#S
\key check > siunitx/detect-family#S
\key check > siunitx/detect-inline-family#S
\key check > siunitx/detect-inline-weight#S
\key check > siunitx/detect-italic#S
\key check > siunitx/detect-mode#S
\key check > siunitx/detect-none#S
\key check > siunitx/detect-shape#S
\key check > siunitx/detect-weight#S
\key check > siunitx/exponent-to-prefix#S
\key check > siunitx/fixed-exponent#S
\key check > siunitx/forbid-literal-units#S
\key check > siunitx/free-standing-units#S
\key check > siunitx/group-digits#S
\key check > siunitx/group-four-digits#S
\key check > siunitx/group-minimum-digits#S
\key check > siunitx/literal-superscript-as-power#S
\key check > siunitx/minimum-integer-digits#S
\key check > siunitx/omit-uncertainty#S
\key check > siunitx/overwrite-functions#S
\key check > siunitx/parse-numbers#S
\key check > siunitx/parse-units#S
\key check > siunitx/prefixes-as-symbols#S
\key check > siunitx/redefine-symbols#S
\key check > siunitx/retain-explicit-plus#S
\key check > siunitx/retain-unity-mantissa#S
\key check > siunitx/retain-zero-exponent#S
\key check > siunitx/round-integer-to-decimal#S
\key check > siunitx/round-precision#S
\key check > siunitx/separate-uncertainty#S
\key check > siunitx/space-before-unit#S
\key check > siunitx/sticky-per#S
\key check > siunitx/table-align-comparator#S
\key check > siunitx/table-align-exponent#S
\key check > siunitx/table-align-text-post#S
\key check > siunitx/table-align-text-pre#S
\key check > siunitx/table-align-uncertainty#S
\key check > siunitx/table-auto-round#S
\key check > siunitx/table-comparator#S
\key check > siunitx/table-omit-exponent#S
\key check > siunitx/table-parse-only#S
\key check > siunitx/table-sign-exponent#S
\key check > siunitx/table-sign-mantissa#S
\key check > siunitx/tight-spacing#S
\key check > siunitx/unit-optional-argument#S
\key check > siunitx/use-xspace#S
\key check > siunitx/version-1-compatibility#S
\key check > siunitx/zero-decimal-to-integer#S
\key code > siunitx/abbreviations#S
\key code > siunitx/abbreviations/false#S
\key code > siunitx/abbreviations/true#S
\key code > siunitx/abbreviations/unknown#S
\key code > siunitx/add-arc-degree-zero#S
\key code > siunitx/add-arc-degree-zero/false#S
\key code > siunitx/add-arc-degree-zero/true#S
\key code > siunitx/add-arc-degree-zero/unknown#S
\key code > siunitx/add-arc-minute-zero#S
\key code > siunitx/add-arc-minute-zero/false#S
\key code > siunitx/add-arc-minute-zero/true#S
\key code > siunitx/add-arc-minute-zero/unknown#S
\key code > siunitx/add-arc-second-zero#S
\key code > siunitx/add-arc-second-zero/false#S
\key code > siunitx/add-arc-second-zero/true#S
\key code > siunitx/add-arc-second-zero/unknown#S
\key code > siunitx/add-decimal-zero#S
\key code > siunitx/add-decimal-zero/false#S
\key code > siunitx/add-decimal-zero/true#S
\key code > siunitx/add-decimal-zero/unknown#S
\key code > siunitx/add-integer-zero#S
\key code > siunitx/add-integer-zero/false#S
\key code > siunitx/add-integer-zero/true#S
\key code > siunitx/add-integer-zero/unknown#S
\key code > siunitx/allow-number-unit-breaks#S
\key code > siunitx/allow-number-unit-breaks/false#S
\key code > siunitx/allow-number-unit-breaks/true#S
\key code > siunitx/allow-number-unit-breaks/unknown#S
\key code > siunitx/angle-symbol-over-decimal#S
\key code > siunitx/angle-symbol-over-decimal/false#S
\key code > siunitx/angle-symbol-over-decimal/true#S
\key code > siunitx/angle-symbol-over-decimal/unknown#S
\key code > siunitx/arc-separator#S
\key code > siunitx/binary-units#S
\key code > siunitx/binary-units/false#S
\key code > siunitx/binary-units/true#S
\key code > siunitx/binary-units/unknown#S
\key code > siunitx/bracket-negative-numbers#S
\key code > siunitx/bracket-negative-numbers/false#S
\key code > siunitx/bracket-negative-numbers/true#S
\key code > siunitx/bracket-negative-numbers/unknown#S
\key code > siunitx/bracket-numbers#S
\key code > siunitx/bracket-numbers/false#S
\key code > siunitx/bracket-numbers/true#S
\key code > siunitx/bracket-numbers/unknown#S
\key code > siunitx/bracket-unit-denominator#S
\key code > siunitx/bracket-unit-denominator/false#S
\key code > siunitx/bracket-unit-denominator/true#S
\key code > siunitx/bracket-unit-denominator/unknown#S
\key code > siunitx/close-bracket#S
\key code > siunitx/color#S
\key code > siunitx/complex-root-position#S
\key code > siunitx/complex-root-position/after-number#S
\key code > siunitx/complex-root-position/before-number#S
\key code > siunitx/complex-root-position/unknown#S
\key code > siunitx/copy-complex-root#S
\key code > siunitx/copy-complex-root/false#S
\key code > siunitx/copy-complex-root/true#S
\key code > siunitx/copy-complex-root/unknown#S
\key code > siunitx/copy-decimal-marker#S
\key code > siunitx/copy-decimal-marker/false#S
\key code > siunitx/copy-decimal-marker/true#S
\key code > siunitx/copy-decimal-marker/unknown#S
\key code > siunitx/detect-all#S
\key code > siunitx/detect-all/false#S
\key code > siunitx/detect-all/true#S
\key code > siunitx/detect-all/unknown#S
\key code > siunitx/detect-display-math#S
\key code > siunitx/detect-display-math/false#S
\key code > siunitx/detect-display-math/true#S
\key code > siunitx/detect-display-math/unknown#S
\key code > siunitx/detect-family#S
\key code > siunitx/detect-family/false#S
\key code > siunitx/detect-family/true#S
\key code > siunitx/detect-family/unknown#S
\key code > siunitx/detect-inline-family#S
\key code > siunitx/detect-inline-family/math#S
\key code > siunitx/detect-inline-family/text#S
\key code > siunitx/detect-inline-family/unknown#S
\key code > siunitx/detect-inline-weight#S
\key code > siunitx/detect-inline-weight/math#S
\key code > siunitx/detect-inline-weight/text#S
\key code > siunitx/detect-inline-weight/unknown#S
\key code > siunitx/detect-italic#S
\key code > siunitx/detect-italic/false#S
\key code > siunitx/detect-italic/true#S
\key code > siunitx/detect-italic/unknown#S
\key code > siunitx/detect-mode#S
\key code > siunitx/detect-mode/false#S
\key code > siunitx/detect-mode/true#S
\key code > siunitx/detect-mode/unknown#S
\key code > siunitx/detect-none#S
\key code > siunitx/detect-none/false#S
\key code > siunitx/detect-none/true#S
\key code > siunitx/detect-none/unknown#S
\key code > siunitx/detect-shape#S
\key code > siunitx/detect-shape/false#S
\key code > siunitx/detect-shape/true#S
\key code > siunitx/detect-shape/unknown#S
\key code > siunitx/detect-weight#S
\key code > siunitx/detect-weight/false#S
\key code > siunitx/detect-weight/true#S
\key code > siunitx/detect-weight/unknown#S
\key code > siunitx/explicit-sign#S
\key code > siunitx/exponent-base#S
\key code > siunitx/exponent-product#S
\key code > siunitx/exponent-to-prefix#S
\key code > siunitx/exponent-to-prefix/false#S
\key code > siunitx/exponent-to-prefix/true#S
\key code > siunitx/exponent-to-prefix/unknown#S
\key code > siunitx/fixed-exponent#S
\key code > siunitx/forbid-literal-units#S
\key code > siunitx/forbid-literal-units/false#S
\key code > siunitx/forbid-literal-units/true#S
\key code > siunitx/forbid-literal-units/unknown#S
\key code > siunitx/fraction-function#S
\key code > siunitx/free-standing-units#S
\key code > siunitx/free-standing-units/false#S
\key code > siunitx/free-standing-units/true#S
\key code > siunitx/free-standing-units/unknown#S
\key code > siunitx/group-decimal-digits#S
\key code > siunitx/group-digits#S
\key code > siunitx/group-digits/decimal#S
\key code > siunitx/group-digits/false#S
\key code > siunitx/group-digits/integer#S
\key code > siunitx/group-digits/true#S
\key code > siunitx/group-digits/unknown#S
\key code > siunitx/group-four-digits#S
\key code > siunitx/group-four-digits/false#S
\key code > siunitx/group-four-digits/true#S
\key code > siunitx/group-four-digits/unknown#S
\key code > siunitx/group-integer-digits#S
\key code > siunitx/group-minimum-digits#S
\key code > siunitx/group-separator#S
\key code > siunitx/input-close-uncertainty#S
\key code > siunitx/input-comparators#S
\key code > siunitx/input-complex-roots#S
\key code > siunitx/input-decimal-markers#S
\key code > siunitx/input-digits#S
\key code > siunitx/input-exponent-markers#S
\key code > siunitx/input-ignore#S
\key code > siunitx/input-open-uncertainty#S
\key code > siunitx/input-product#S
\key code > siunitx/input-protect-tokens#S
\key code > siunitx/input-quotient#S
\key code > siunitx/input-signs#S
\key code > siunitx/input-symbols#S
\key code > siunitx/input-uncertainty-signs#S
\key code > siunitx/inter-unit-product#S
\key code > siunitx/inter-unit-separator#S
\key code > siunitx/list-final-separator#S
\key code > siunitx/list-pair-separator#S
\key code > siunitx/list-separator#S
\key code > siunitx/list-units#S
\key code > siunitx/list-units/brackets#S
\key code > siunitx/list-units/repeat#S
\key code > siunitx/list-units/single#S
\key code > siunitx/list-units/unknown#S
\key code > siunitx/literal-superscript-as-power#S
\key code > siunitx/literal-superscript-as-power/false#S
\key code > siunitx/literal-superscript-as-power/true#S
\key code > siunitx/literal-superscript-as-power/unknown#S
\key code > siunitx/load-configurations#S
\key code > siunitx/locale#S
\key code > siunitx/locale/DE#S
\key code > siunitx/locale/FR#S
\key code > siunitx/locale/UK#S
\key code > siunitx/locale/US#S
\key code > siunitx/locale/USA#S
\key code > siunitx/locale/ZA#S
\key code > siunitx/locale/unknown#S
\key code > siunitx/math-angstrom#S
\key code > siunitx/math-arcminute#S
\key code > siunitx/math-arcsecond#S
\key code > siunitx/math-celsius#S
\key code > siunitx/math-degree#S
\key code > siunitx/math-micro#S
\key code > siunitx/math-ohm#S
\key code > siunitx/math-rm#S
\key code > siunitx/math-sf#S
\key code > siunitx/math-tt#S
\key code > siunitx/minimum-integer-digits#S
\key code > siunitx/mode#S
\key code > siunitx/mode/math#S
\key code > siunitx/mode/text#S
\key code > siunitx/mode/unknown#S
\key code > siunitx/multi-part-units#S
\key code > siunitx/multi-part-units/brackets#S
\key code > siunitx/multi-part-units/repeat#S
\key code > siunitx/multi-part-units/single#S
\key code > siunitx/multi-part-units/unknown#S
\key code > siunitx/negative-color#S
\key code > siunitx/number-angle-product#S
\key code > siunitx/number-angle-separator#S
\key code > siunitx/number-color#S
\key code > siunitx/number-math-rm#S
\key code > siunitx/number-math-sf#S
\key code > siunitx/number-math-tt#S
\key code > siunitx/number-mode#S
\key code > siunitx/number-mode/math#S
\key code > siunitx/number-mode/text#S
\key code > siunitx/number-mode/unknown#S
\key code > siunitx/number-text-rm#S
\key code > siunitx/number-text-sf#S
\key code > siunitx/number-text-tt#S
\key code > siunitx/number-unit-product#S
\key code > siunitx/number-unit-separator#S
\key code > siunitx/omit-uncertainty#S
\key code > siunitx/omit-uncertainty/false#S
\key code > siunitx/omit-uncertainty/true#S
\key code > siunitx/omit-uncertainty/unknown#S
\key code > siunitx/open-bracket#S
\key code > siunitx/output-close-uncertainty#S
\key code > siunitx/output-complex-root#S
\key code > siunitx/output-decimal-marker#S
\key code > siunitx/output-exponent-marker#S
\key code > siunitx/output-open-uncertainty#S
\key code > siunitx/output-product#S
\key code > siunitx/output-quotient#S
\key code > siunitx/overwrite-functions#S
\key code > siunitx/overwrite-functions/false#S
\key code > siunitx/overwrite-functions/true#S
\key code > siunitx/overwrite-functions/unknown#S
\key code > siunitx/parse-numbers#S
\key code > siunitx/parse-numbers/false#S
\key code > siunitx/parse-numbers/true#S
\key code > siunitx/parse-numbers/unknown#S
\key code > siunitx/parse-units#S
\key code > siunitx/parse-units/false#S
\key code > siunitx/parse-units/true#S
\key code > siunitx/parse-units/unknown#S
\key code > siunitx/per-mode#S
\key code > siunitx/per-mode/fraction#S
\key code > siunitx/per-mode/power#S
\key code > siunitx/per-mode/power-positive-first#S
\key code > siunitx/per-mode/reciprocal#S
\key code > siunitx/per-mode/reciprocal-positive-first#S
\key code > siunitx/per-mode/repeated-symbol#S
\key code > siunitx/per-mode/symbol#S
\key code > siunitx/per-mode/symbol-or-fraction#S
\key code > siunitx/per-mode/unknown#S
\key code > siunitx/per-symbol#S
\key code > siunitx/power-font#S
\key code > siunitx/power-font/number#S
\key code > siunitx/power-font/unit#S
\key code > siunitx/power-font/unknown#S
\key code > siunitx/prefixes-as-symbols#S
\key code > siunitx/prefixes-as-symbols/false#S
\key code > siunitx/prefixes-as-symbols/true#S
\key code > siunitx/prefixes-as-symbols/unknown#S
\key code > siunitx/preunit#S
\key code > siunitx/product-units#S
\key code > siunitx/product-units/brackets#S
\key code > siunitx/product-units/brackets-power#S
\key code > siunitx/product-units/power#S
\key code > siunitx/product-units/repeat#S
\key code > siunitx/product-units/single#S
\key code > siunitx/product-units/unknown#S
\key code > siunitx/qualifier-mode#S
\key code > siunitx/qualifier-mode/brackets#S
\key code > siunitx/qualifier-mode/phrase#S
\key code > siunitx/qualifier-mode/space#S
\key code > siunitx/qualifier-mode/subscript#S
\key code > siunitx/qualifier-mode/text#S
\key code > siunitx/qualifier-mode/unknown#S
\key code > siunitx/qualifier-phrase#S
\key code > siunitx/quotient-mode#S
\key code > siunitx/quotient-mode/fraction#S
\key code > siunitx/quotient-mode/symbol#S
\key code > siunitx/quotient-mode/unknown#S
\key code > siunitx/range-phrase#S
\key code > siunitx/range-units#S
\key code > siunitx/range-units/brackets#S
\key code > siunitx/range-units/repeat#S
\key code > siunitx/range-units/single#S
\key code > siunitx/range-units/unknown#S
\key code > siunitx/redefine-symbols#S
\key code > siunitx/redefine-symbols/false#S
\key code > siunitx/redefine-symbols/true#S
\key code > siunitx/redefine-symbols/unknown#S
\key code > siunitx/retain-explicit-plus#S
\key code > siunitx/retain-explicit-plus/false#S
\key code > siunitx/retain-explicit-plus/true#S
\key code > siunitx/retain-explicit-plus/unknown#S
\key code > siunitx/retain-unity-mantissa#S
\key code > siunitx/retain-unity-mantissa/false#S
\key code > siunitx/retain-unity-mantissa/true#S
\key code > siunitx/retain-unity-mantissa/unknown#S
\key code > siunitx/retain-zero-exponent#S
\key code > siunitx/retain-zero-exponent/false#S
\key code > siunitx/retain-zero-exponent/true#S
\key code > siunitx/retain-zero-exponent/unknown#S
\key code > siunitx/round-half#S
\key code > siunitx/round-half/even#S
\key code > siunitx/round-half/unknown#S
\key code > siunitx/round-half/up#S
\key code > siunitx/round-integer-to-decimal#S
\key code > siunitx/round-integer-to-decimal/false#S
\key code > siunitx/round-integer-to-decimal/true#S
\key code > siunitx/round-integer-to-decimal/unknown#S
\key code > siunitx/round-minimum#S
\key code > siunitx/round-mode#S
\key code > siunitx/round-mode/figures#S
\key code > siunitx/round-mode/off#S
\key code > siunitx/round-mode/places#S
\key code > siunitx/round-mode/unknown#S
\key code > siunitx/round-precision#S
\key code > siunitx/scientific-notation#S
\key code > siunitx/scientific-notation/engineering#S
\key code > siunitx/scientific-notation/false#S
\key code > siunitx/scientific-notation/fixed#S
\key code > siunitx/scientific-notation/true#S
\key code > siunitx/scientific-notation/unknown#S
\key code > siunitx/separate-uncertainty#S
\key code > siunitx/separate-uncertainty/false#S
\key code > siunitx/separate-uncertainty/true#S
\key code > siunitx/separate-uncertainty/unknown#S
\key code > siunitx/space-before-unit#S
\key code > siunitx/space-before-unit/false#S
\key code > siunitx/space-before-unit/true#S
\key code > siunitx/space-before-unit/unknown#S
\key code > siunitx/sticky-per#S
\key code > siunitx/sticky-per/false#S
\key code > siunitx/sticky-per/true#S
\key code > siunitx/sticky-per/unknown#S
\key code > siunitx/strict#S
\key code > siunitx/table-align-comparator#S
\key code > siunitx/table-align-comparator/false#S
\key code > siunitx/table-align-comparator/true#S
\key code > siunitx/table-align-comparator/unknown#S
\key code > siunitx/table-align-exponent#S
\key code > siunitx/table-align-exponent/false#S
\key code > siunitx/table-align-exponent/true#S
\key code > siunitx/table-align-exponent/unknown#S
\key code > siunitx/table-align-text-post#S
\key code > siunitx/table-align-text-post/false#S
\key code > siunitx/table-align-text-post/true#S
\key code > siunitx/table-align-text-post/unknown#S
\key code > siunitx/table-align-text-pre#S
\key code > siunitx/table-align-text-pre/false#S
\key code > siunitx/table-align-text-pre/true#S
\key code > siunitx/table-align-text-pre/unknown#S
\key code > siunitx/table-align-uncertainty#S
\key code > siunitx/table-align-uncertainty/false#S
\key code > siunitx/table-align-uncertainty/true#S
\key code > siunitx/table-align-uncertainty/unknown#S
\key code > siunitx/table-alignment#S
\key code > siunitx/table-auto-round#S
\key code > siunitx/table-auto-round/false#S
\key code > siunitx/table-auto-round/true#S
\key code > siunitx/table-auto-round/unknown#S
\key code > siunitx/table-column-width#S
\key code > siunitx/table-comparator#S
\key code > siunitx/table-comparator/false#S
\key code > siunitx/table-comparator/true#S
\key code > siunitx/table-comparator/unknown#S
\key code > siunitx/table-figures-decimal#S
\key code > siunitx/table-figures-exponent#S
\key code > siunitx/table-figures-integer#S
\key code > siunitx/table-figures-uncertainty#S
\key code > siunitx/table-format#S
\key code > siunitx/table-number-alignment#S
\key code > siunitx/table-number-alignment/center#S
\key code > siunitx/table-number-alignment/left#S
\key code > siunitx/table-number-alignment/right#S
\key code > siunitx/table-number-alignment/unknown#S
\key code > siunitx/table-omit-exponent#S
\key code > siunitx/table-omit-exponent/false#S
\key code > siunitx/table-omit-exponent/true#S
\key code > siunitx/table-omit-exponent/unknown#S
\key code > siunitx/table-parse-only#S
\key code > siunitx/table-parse-only/false#S
\key code > siunitx/table-parse-only/true#S
\key code > siunitx/table-parse-only/unknown#S
\key code > siunitx/table-sign-exponent#S
\key code > siunitx/table-sign-exponent/false#S
\key code > siunitx/table-sign-exponent/true#S
\key code > siunitx/table-sign-exponent/unknown#S
\key code > siunitx/table-sign-mantissa#S
\key code > siunitx/table-sign-mantissa/false#S
\key code > siunitx/table-sign-mantissa/true#S
\key code > siunitx/table-sign-mantissa/unknown#S
\key code > siunitx/table-space-text-post#S
\key code > siunitx/table-space-text-pre#S
\key code > siunitx/table-text-alignment#S
\key code > siunitx/table-text-alignment/center#S
\key code > siunitx/table-text-alignment/left#S
\key code > siunitx/table-text-alignment/right#S
\key code > siunitx/table-text-alignment/unknown#S
\key code > siunitx/table-unit-alignment#S
\key code > siunitx/table-unit-alignment/center#S
\key code > siunitx/table-unit-alignment/left#S
\key code > siunitx/table-unit-alignment/right#S
\key code > siunitx/table-unit-alignment/unknown#S
\key code > siunitx/text-angstrom#S
\key code > siunitx/text-arcminute#S
\key code > siunitx/text-arcsecond#S
\key code > siunitx/text-celsius#S
\key code > siunitx/text-degree#S
\key code > siunitx/text-micro#S
\key code > siunitx/text-ohm#S
\key code > siunitx/text-rm#S
\key code > siunitx/text-sf#S
\key code > siunitx/text-tt#S
\key code > siunitx/tight-spacing#S
\key code > siunitx/tight-spacing/false#S
\key code > siunitx/tight-spacing/true#S
\key code > siunitx/tight-spacing/unknown#S
\key code > siunitx/uncertainty-separator#S
\key code > siunitx/unit-color#S
\key code > siunitx/unit-math-rm#S
\key code > siunitx/unit-math-sf#S
\key code > siunitx/unit-math-tt#S
\key code > siunitx/unit-mode#S
\key code > siunitx/unit-mode/math#S
\key code > siunitx/unit-mode/text#S
\key code > siunitx/unit-mode/unknown#S
\key code > siunitx/unit-optional-argument#S
\key code > siunitx/unit-optional-argument/false#S
\key code > siunitx/unit-optional-argument/true#S
\key code > siunitx/unit-optional-argument/unknown#S
\key code > siunitx/unit-text-rm#S
\key code > siunitx/unit-text-sf#S
\key code > siunitx/unit-text-tt#S
\key code > siunitx/unknown#S
\key code > siunitx/use-xspace#S
\key code > siunitx/use-xspace/false#S
\key code > siunitx/use-xspace/true#S
\key code > siunitx/use-xspace/unknown#S
\key code > siunitx/version-1-compatibility#S
\key code > siunitx/version-1-compatibility/false#S
\key code > siunitx/version-1-compatibility/true#S
\key code > siunitx/version-1-compatibility/unknown#S
\key code > siunitx/zero-decimal-to-integer#S
\key code > siunitx/zero-decimal-to-integer/false#S
\key code > siunitx/zero-decimal-to-integer/true#S
\key code > siunitx/zero-decimal-to-integer/unknown#S
\key default > siunitx/abbreviations#S
\key default > siunitx/add-arc-degree-zero#S
\key default > siunitx/add-arc-minute-zero#S
\key default > siunitx/add-arc-second-zero#S
\key default > siunitx/add-decimal-zero#S
\key default > siunitx/add-integer-zero#S
\key default > siunitx/allow-number-unit-breaks#S
\key default > siunitx/angle-symbol-over-decimal#S
\key default > siunitx/binary-units#S
\key default > siunitx/bracket-negative-numbers#S
\key default > siunitx/bracket-numbers#S
\key default > siunitx/bracket-unit-denominator#S
\key default > siunitx/copy-complex-root#S
\key default > siunitx/copy-decimal-marker#S
\key default > siunitx/detect-all#S
\key default > siunitx/detect-display-math#S
\key default > siunitx/detect-family#S
\key default > siunitx/detect-italic#S
\key default > siunitx/detect-mode#S
\key default > siunitx/detect-none#S
\key default > siunitx/detect-shape#S
\key default > siunitx/detect-weight#S
\key default > siunitx/exponent-to-prefix#S
\key default > siunitx/forbid-literal-units#S
\key default > siunitx/free-standing-units#S
\key default > siunitx/group-digits#S
\key default > siunitx/group-four-digits#S
\key default > siunitx/literal-superscript-as-power#S
\key default > siunitx/omit-uncertainty#S
\key default > siunitx/overwrite-functions#S
\key default > siunitx/parse-numbers#S
\key default > siunitx/parse-units#S
\key default > siunitx/prefixes-as-symbols#S
\key default > siunitx/redefine-symbols#S
\key default > siunitx/retain-explicit-plus#S
\key default > siunitx/retain-unity-mantissa#S
\key default > siunitx/retain-zero-exponent#S
\key default > siunitx/round-integer-to-decimal#S
\key default > siunitx/separate-uncertainty#S
\key default > siunitx/space-before-unit#S
\key default > siunitx/sticky-per#S
\key default > siunitx/table-align-comparator#S
\key default > siunitx/table-align-exponent#S
\key default > siunitx/table-align-text-post#S
\key default > siunitx/table-align-text-pre#S
\key default > siunitx/table-align-uncertainty#S
\key default > siunitx/table-auto-round#S
\key default > siunitx/table-comparator#S
\key default > siunitx/table-omit-exponent#S
\key default > siunitx/table-parse-only#S
\key default > siunitx/table-sign-exponent#S
\key default > siunitx/table-sign-mantissa#S
\key default > siunitx/tight-spacing#S
\key default > siunitx/unit-optional-argument#S
\key default > siunitx/use-xspace#S
\key default > siunitx/version-1-compatibility#S
\key default > siunitx/zero-decimal-to-integer#S
\key type > siunitx/abbreviations#S
\key type > siunitx/add-arc-degree-zero#S
\key type > siunitx/add-arc-minute-zero#S
\key type > siunitx/add-arc-second-zero#S
\key type > siunitx/add-decimal-zero#S
\key type > siunitx/add-integer-zero#S
\key type > siunitx/allow-number-unit-breaks#S
\key type > siunitx/angle-symbol-over-decimal#S
\key type > siunitx/binary-units#S
\key type > siunitx/bracket-negative-numbers#S
\key type > siunitx/bracket-numbers#S
\key type > siunitx/bracket-unit-denominator#S
\key type > siunitx/complex-root-position#S
\key type > siunitx/copy-complex-root#S
\key type > siunitx/copy-decimal-marker#S
\key type > siunitx/detect-all#S
\key type > siunitx/detect-display-math#S
\key type > siunitx/detect-family#S
\key type > siunitx/detect-inline-family#S
\key type > siunitx/detect-inline-weight#S
\key type > siunitx/detect-italic#S
\key type > siunitx/detect-mode#S
\key type > siunitx/detect-none#S
\key type > siunitx/detect-shape#S
\key type > siunitx/detect-weight#S
\key type > siunitx/exponent-to-prefix#S
\key type > siunitx/forbid-literal-units#S
\key type > siunitx/free-standing-units#S
\key type > siunitx/group-digits#S
\key type > siunitx/group-four-digits#S
\key type > siunitx/list-units#S
\key type > siunitx/literal-superscript-as-power#S
\key type > siunitx/locale#S
\key type > siunitx/mode#S
\key type > siunitx/multi-part-units#S
\key type > siunitx/number-mode#S
\key type > siunitx/omit-uncertainty#S
\key type > siunitx/overwrite-functions#S
\key type > siunitx/parse-numbers#S
\key type > siunitx/parse-units#S
\key type > siunitx/per-mode#S
\key type > siunitx/power-font#S
\key type > siunitx/prefixes-as-symbols#S
\key type > siunitx/product-units#S
\key type > siunitx/qualifier-mode#S
\key type > siunitx/quotient-mode#S
\key type > siunitx/range-units#S
\key type > siunitx/redefine-symbols#S
\key type > siunitx/retain-explicit-plus#S
\key type > siunitx/retain-unity-mantissa#S
\key type > siunitx/retain-zero-exponent#S
\key type > siunitx/round-half#S
\key type > siunitx/round-integer-to-decimal#S
\key type > siunitx/round-mode#S
\key type > siunitx/scientific-notation#S
\key type > siunitx/separate-uncertainty#S
\key type > siunitx/space-before-unit#S
\key type > siunitx/sticky-per#S
\key type > siunitx/table-align-comparator#S
\key type > siunitx/table-align-exponent#S
\key type > siunitx/table-align-text-post#S
\key type > siunitx/table-align-text-pre#S
\key type > siunitx/table-align-uncertainty#S
\key type > siunitx/table-auto-round#S
\key type > siunitx/table-comparator#S
\key type > siunitx/table-number-alignment#S
\key type > siunitx/table-omit-exponent#S
\key type > siunitx/table-parse-only#S
\key type > siunitx/table-sign-exponent#S
\key type > siunitx/table-sign-mantissa#S
\key type > siunitx/table-text-alignment#S
\key type > siunitx/table-unit-alignment#S
\key type > siunitx/tight-spacing#S
\key type > siunitx/unit-mode#S
\key type > siunitx/unit-optional-argument#S
\key type > siunitx/use-xspace#S
\key type > siunitx/version-1-compatibility#S
\key type > siunitx/zero-decimal-to-integer#S
\l__siunitx_\arcmin_options_tl#S
\l__siunitx_\arcminute_options_tl#S
\l__siunitx_\arcsecond_options_tl#S
\l__siunitx_\degree_options_tl#S
\l_peek_token#S
\msg extra text > siunitx/bad-arc-sign#S
\msg extra text > siunitx/color-not-loaded#S
\msg extra text > siunitx/duplicate-complex-root-token#S
\msg extra text > siunitx/duplicate-decimal-token#S
\msg extra text > siunitx/duplicate-exponent-token#S
\msg extra text > siunitx/duplicate-quotient-token#S
\msg extra text > siunitx/duplicate-sticky-per#S
\msg extra text > siunitx/empty-arc#S
\msg extra text > siunitx/empty-uncertainty#S
\msg extra text > siunitx/ending-product-token#S
\msg extra text > siunitx/ending-quotient-token#S
\msg extra text > siunitx/incompatible-package#S
\msg extra text > siunitx/invalid-arc-format#S
\msg extra text > siunitx/invalid-number#S
\msg extra text > siunitx/invalid-token-in-exponent#S
\msg extra text > siunitx/invalid-token-in-number#S
\msg extra text > siunitx/invalid-token-in-uncertainty#S
\msg extra text > siunitx/literal-unit#S
\msg extra text > siunitx/misplaced-complex-root-token#S
\msg extra text > siunitx/misplaced-sign-token#S
\msg extra text > siunitx/misplaced-uncertainty-token#S
\msg extra text > siunitx/multi-part-range#S
\msg extra text > siunitx/non-convertible-exponent#S
\msg extra text > siunitx/option-not-available#S
\msg extra text > siunitx/option-preamble-only#S
\msg extra text > siunitx/prefix-base-mismatch#S
\msg extra text > siunitx/prefix-only#S
\msg extra text > siunitx/qualifier-before-unit#S
\msg extra text > siunitx/restricted-number#S
\msg extra text > siunitx/starting-product-token#S
\msg extra text > siunitx/starting-quotient-token#S
\msg extra text > siunitx/table-partial-number#S
\msg extra text > siunitx/unknown-option#S
\msg extra text > siunitx/version-1-option#S
\msg text > siunitx/bad-arc-sign#S
\msg text > siunitx/color-not-loaded#S
\msg text > siunitx/duplicate-complex-root-token#S
\msg text > siunitx/duplicate-decimal-token#S
\msg text > siunitx/duplicate-exponent-token#S
\msg text > siunitx/duplicate-quotient-token#S
\msg text > siunitx/duplicate-sticky-per#S
\msg text > siunitx/empty-arc#S
\msg text > siunitx/empty-uncertainty#S
\msg text > siunitx/ending-product-token#S
\msg text > siunitx/ending-quotient-token#S
\msg text > siunitx/incompatible-package#S
\msg text > siunitx/invalid-arc-format#S
\msg text > siunitx/invalid-number#S
\msg text > siunitx/invalid-token-in-exponent#S
\msg text > siunitx/invalid-token-in-number#S
\msg text > siunitx/invalid-token-in-uncertainty#S
\msg text > siunitx/literal-unit#S
\msg text > siunitx/misplaced-complex-root-token#S
\msg text > siunitx/misplaced-sign-token#S
\msg text > siunitx/misplaced-uncertainty-token#S
\msg text > siunitx/multi-part-range#S
\msg text > siunitx/non-convertible-exponent#S
\msg text > siunitx/option-not-available#S
\msg text > siunitx/option-preamble-only#S
\msg text > siunitx/prefix-base-mismatch#S
\msg text > siunitx/prefix-only#S
\msg text > siunitx/qualifier-before-unit#S
\msg text > siunitx/restricted-number#S
\msg text > siunitx/starting-product-token#S
\msg text > siunitx/starting-quotient-token#S
\msg text > siunitx/table-partial-number#S
\msg text > siunitx/unknown-option#S
\msg text > siunitx/version-1-option#S
\num code#S
\numInBookmark (arg 1)#S
\numInBookmark code#S
\numlist code#S
\numrange code#S
\numrangeInBookmark (arg 1)#S
\numrangeInBookmark code#S
\si code#S
\siInBookmark (arg 1)#S
\siInBookmark code#S
\sisetup code#S
\tablenum code#S
\tl_if_empty:fT#S
\tl_if_empty_p:f#S
\tl_replace_all:Non#S
\unprocessedoptions-amstext.sty#S
\unprocessedoptions-array.sty#S
\unprocessedoptions-expl3.sty#S
\unprocessedoptions-l3keys2e.sty#S
\unprocessedoptions-translator.sty#S
\unprocessedoptions-xparse.sty#S
amstext.sty#S
array.sty#S
csnameendcsname#S
expl3.sty#S
l3keys2e.sty#S
translator.sty#S
xparse.sty#S
